config/routes.rb
Bookstore::Application.routes.draw do
  resources :reviews

  #get "/books" => "books#index", as: 'books'
  #get "/books/new" => "books#new", as: 'new_book'
  #get "/books/:id" => "books#show", as: 'book'
  #post "/books" => "books#create"
  #get "/books/:id/edit" => "books#edit", as: 'edit_book'
  #patch "/books/:id" => "books#update"
  #delete "/books/:id" => "books#destroy"
  resources :books do
    resources :reviews
    get 'page/:page', :action => :index, :on => :collection
  end
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  scope :bargains, -> { where('price < 10.00') }
  scope :by, ->(author) { where('author = ?', author) }
  validates :title, :author, :pages, :price, presence: true
  validates :pages,
   numericality: { only_integer: true, greater_than_or_equal_to: 0 },
   unless: "pages.blank?"
  validates :price, 
    numericality: { greater_than_or_equal_to: 0 },
    if: "price.present?"
  has_many :reviews, dependent: :destroy
  def average_stars
    if reviews.loaded?
      reviews.map(&:stars).compact.average
    else
      reviews.average(:stars)
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  STARS = 1..5
  validates :name, :comment, presence: true
  validates :comment, length: { minimum: 15}, unless: 'comment.blank?'
  validates :stars, inclusion: { in: STARS, message: "must be from #{STARS.first} to #{STARS.last}" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :set_book, only: [ :show, :edit, :update, :destroy ]
	def index
  		@available_at = Time.now
  		@books = Book.includes(:reviews).order(:title).page(params[:page])
	end
	def show
	end
	def new
	  @book = Book.new
	end

	def create
	  @book = Book.new(book_params)
	  if @book.save
	    redirect_to @book, notice: "#{@book.title} was created!"
	  else
	  	render :new
	  end
	end

	def edit
	end

	def update
	  if @book.update(book_params)
	    redirect_to @book, notice: "#{@book.title} was updated!"
	  else
	  	render :new
	  end
	end
	def destroy
	  @book.destroy
	  redirect_to books_url
	end
	private

	def book_params
	  params.require(:book).permit(:title, :author, :pages, :price)
	end
	def set_book
  		@book = Book.find(params[:id])
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book

  def index
  	@reviews = @book.reviews.order('created_at desc')
  end

  def new
  	@review = @book.reviews.new
  end

  def create
  	@review = @book.reviews.new(review_params)
  	if @review.save
  		redirect_to book_reviews_path(@book), notice: 'Review saved!'
  	else
  		render :new
  	end
  end

  private

  def set_book
  	@book = Book.find(params[:book_id])
  end

  def review_params
  	params.require(:review).permit(:stars, :name, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper

	def formatted_time(time)

	time.strftime("%B %d, %Y at %l:%M %p")

	end
  def format_average_stars(book)
    average = book.average_stars
    if average
      pluralize(number_with_precision(average, precision: 1), 'star')
    else
      'No reviews'
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <%= render 'shared/validation_errors', object: @book %>
  <%= f.label :title %> <%= f.text_field :title, autofocus: true %><br />
  <%= f.label :author %> <%= f.text_field :author %><br />
  <%= f.label :pages %> <%= f.text_field :pages %><br />
  <%= f.label :price %> <%= f.text_field :price %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', books_path %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book <%= @book.title %></h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h1>Books</h1>

<p>Available as of <%=formatted_time(@available_at) %></p>

<ol>

<% @books.each do |book| %>

<li>
  <%= link_to(book.title, book) %>
  by <%= book.author %><br/>
  <%= format_average_stars(book) %>
  <% if book.reviews.any? %>
    (out of <%= pluralize(book.reviews.size, 'review') %>)
  <% end %>
</li>

<% end %>

</ol>
<%= paginate @books %>

app/views/books/new.html.erb
<h1>Create a New Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<% content_for :title, @book.title %>
<article class="book">
  <header>
    <h2><%= @book.title %></h2>
  </header>
  <p><label>Author:</label> <%= @book.author %></p>
  <p><label>Pages:</label> <%= number_with_delimiter(@book.pages) %></p>
  <p><label>Price:</label> <%= number_to_currency(@book.price) %></p>
  <p><label>Average Review:</label> <%= format_average_stars(@book) %></p>
</article>

<%= link_to 'All Books', books_path %>
| <%= link_to 'Edit', edit_book_path(@book) %>
<%= button_to 'Delete', @book,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<p>
  Read all
  <%= link_to pluralize(@book.reviews.size, 'review'), book_reviews_path(@book) %>
</p>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Awesome Books', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Navigation</h3>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to 'All Books', books_path %>
    </p>
    <p>
      <%= link_to 'Create Book', new_book_path %>
    </p>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome Books <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([ @book, @review ]) do |f| %>
  <%= render 'shared/validation_errors', object: @review %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name' %><br />
  <%= f.label :stars %>
  <% Review::STARS.each do |star| %>
    <%= f.radio_button :stars, star %> <%= star %>
    <% end %><br />
  <%= f.label :comment %><br />
  <%= f.text_area :comment %><br />
  <p>
  	<%= f.submit %>
  	<%= link_to 'Cancel', book_reviews_path(@book), id: 'cancel_review' %>
  </p>
  <% end %>

app/views/reviews/index.html.erb
<header>Reviews for <%= link_to(@book.title, @book) %></header>
<ol id="reviews">
  <% @reviews.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.stars, 'star') %></span>
      <span class="user">by <%= review.name %> </span>
      <span class="date">
        <%= time_ago_in_words(review.created_at) %> ago
      </span>
      <p>
        &quot;<%= review.comment %>&quot;
      </p>
  </li>
  <% end %>
</ol>
<%= link_to 'Write a Review', new_book_review_path(@book),
        remote: true,
        data: { 'update-target' => 'review_form_container' },
        class: 'btn btn-primary' %>

<div id="review_form_container"></div>

app/views/reviews/new.html.erb
<h1>Write a review for <%= @book.title %></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>